/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pfilesharing.UI;

import java.util.ArrayList;
import java.util.concurrent.CopyOnWriteArrayList;
import javax.swing.DefaultListModel;
import p2pfilesharing.FileInfo;
import p2pfilesharing.UdpPeerReceive;

/**
 *
 * @author Luís Maia
 */
public class MainFrame extends javax.swing.JFrame {

    private String entry;
    private String dwnIp;
    private String dwnFileName;
    private DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form MainFrame
     *
     * @param nick
     */
    public MainFrame(String nick) {
        initComponents();
        this.entry = "";
        welcome_txtfield.setText("Welcome " + nick);
    }

    public String getDwnIp() {
        return dwnIp;
    }

    public void setDwnIp(String dwnIp) {
        this.dwnIp = dwnIp;
    }

    public String getDwnFileName() {
        return dwnFileName;
    }

    public void setDwnFileName(String dwnFileName) {
        this.dwnFileName = dwnFileName;
    }

    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    public void setMessageText(String text) {
        mess_label.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        files_list = new javax.swing.JList<>();
        dwnl_bt = new javax.swing.JButton();
        inst_label = new javax.swing.JLabel();
        mess_label = new javax.swing.JLabel();
        welcome_txtfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P2P FILE SHARING");

        jScrollPane1.setViewportView(files_list);

        dwnl_bt.setText("DOWNLOAD");
        dwnl_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwnl_btActionPerformed(evt);
            }
        });

        inst_label.setText("Select a File to Download");

        mess_label.setText("press to download");

        welcome_txtfield.setText("Welcome ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dwnl_bt)
                            .addComponent(mess_label)))
                    .addComponent(inst_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(welcome_txtfield)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcome_txtfield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inst_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dwnl_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mess_label)
                        .addGap(68, 68, 68)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dwnl_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwnl_btActionPerformed
        FileInfo f = files_list.getSelectedValue();
        if (f != null) {
            setDwnIp(f.getEndereco_Servidor());
            setDwnFileName(f.getNome_Ficheiro());
            setEntry("Download");
        }
    }//GEN-LAST:event_dwnl_btActionPerformed
    public void updateList() {
        ArrayList<FileInfo> fi;
        for (CopyOnWriteArrayList<FileInfo> value : UdpPeerReceive.mapa_Servidor_Ficheiros.values()) {
            listModel = new DefaultListModel();
            for (FileInfo fileInfo : value) {
                listModel.addElement(fileInfo);
            }
        }
        files_list.setModel(listModel);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dwnl_bt;
    private javax.swing.JList<FileInfo> files_list;
    private javax.swing.JLabel inst_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mess_label;
    private javax.swing.JLabel welcome_txtfield;
    // End of variables declaration//GEN-END:variables
}
